[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "node --max-old-space-size=300 --expose-gc src/server.js"
healthcheckPath = "/health"
healthcheckTimeout = 300

[env]
TZ = "America/Sao_Paulo"
