ALTER TABLE "messages" DROP CONSTRAINT "messages_provider_message_id_unique";--> statement-breakpoint
CREATE INDEX "agency_approvals_company_id_idx" ON "agency_approvals" USING btree ("company_id");--> statement-breakpoint
CREATE INDEX "agency_campaigns_company_id_idx" ON "agency_campaigns" USING btree ("company_id");--> statement-breakpoint
CREATE INDEX "agency_clients_company_id_idx" ON "agency_clients" USING btree ("company_id");--> statement-breakpoint
CREATE INDEX "agency_comments_company_id_idx" ON "agency_comments" USING btree ("company_id");--> statement-breakpoint
CREATE INDEX "agency_contents_company_id_idx" ON "agency_contents" USING btree ("company_id");--> statement-breakpoint
CREATE INDEX "agency_materials_company_id_idx" ON "agency_materials" USING btree ("company_id");--> statement-breakpoint
CREATE INDEX "agency_tasks_company_id_idx" ON "agency_tasks" USING btree ("company_id");--> statement-breakpoint
CREATE INDEX "agent_commissions_company_id_idx" ON "agent_commissions" USING btree ("company_id");--> statement-breakpoint
CREATE INDEX "ai_followup_queue_company_id_idx" ON "ai_followup_queue" USING btree ("company_id");--> statement-breakpoint
CREATE INDEX "ai_usage_daily_company_id_idx" ON "ai_usage_daily" USING btree ("company_id");--> statement-breakpoint
CREATE INDEX "alert_rules_company_id_idx" ON "alert_rules" USING btree ("company_id");--> statement-breakpoint
CREATE INDEX "alerts_company_id_idx" ON "alerts" USING btree ("company_id");--> statement-breakpoint
CREATE INDEX "automation_logs_company_id_idx" ON "automation_logs" USING btree ("company_id");--> statement-breakpoint
CREATE INDEX "automation_rules_company_id_idx" ON "automation_rules" USING btree ("company_id");--> statement-breakpoint
CREATE INDEX "baileys_messages_connection_id_idx" ON "baileys_messages" USING btree ("connection_id");--> statement-breakpoint
CREATE INDEX "cadence_definitions_company_id_idx" ON "cadence_definitions" USING btree ("company_id");--> statement-breakpoint
CREATE INDEX "cadence_enrollments_contact_id_idx" ON "cadence_enrollments" USING btree ("contact_id");--> statement-breakpoint
CREATE INDEX "campaigns_company_id_idx" ON "campaigns" USING btree ("company_id");--> statement-breakpoint
CREATE INDEX "campaigns_connection_id_idx" ON "campaigns" USING btree ("connection_id");--> statement-breakpoint
CREATE INDEX "company_feature_access_company_id_idx" ON "company_feature_access" USING btree ("company_id");--> statement-breakpoint
CREATE INDEX "connections_company_id_idx" ON "connections" USING btree ("company_id");--> statement-breakpoint
CREATE INDEX "contact_events_company_id_idx" ON "contact_events" USING btree ("company_id");--> statement-breakpoint
CREATE INDEX "contact_events_contact_id_idx" ON "contact_events" USING btree ("contact_id");--> statement-breakpoint
CREATE INDEX "contact_lists_company_id_idx" ON "contact_lists" USING btree ("company_id");--> statement-breakpoint
CREATE INDEX "contacts_company_id_idx" ON "contacts" USING btree ("company_id");--> statement-breakpoint
CREATE INDEX "contacts_to_contact_lists_company_id_idx" ON "contacts_to_contact_lists" USING btree ("company_id");--> statement-breakpoint
CREATE INDEX "contacts_to_contact_lists_contact_id_idx" ON "contacts_to_contact_lists" USING btree ("contact_id");--> statement-breakpoint
CREATE INDEX "contacts_to_tags_company_id_idx" ON "contacts_to_tags" USING btree ("company_id");--> statement-breakpoint
CREATE INDEX "contacts_to_tags_contact_id_idx" ON "contacts_to_tags" USING btree ("contact_id");--> statement-breakpoint
CREATE INDEX "conversations_company_id_idx" ON "conversations" USING btree ("company_id");--> statement-breakpoint
CREATE INDEX "conversations_contact_id_idx" ON "conversations" USING btree ("contact_id");--> statement-breakpoint
CREATE INDEX "conversations_connection_id_idx" ON "conversations" USING btree ("connection_id");--> statement-breakpoint
CREATE INDEX "kanban_leads_company_id_idx" ON "kanban_leads" USING btree ("company_id");--> statement-breakpoint
CREATE INDEX "kanban_leads_contact_id_idx" ON "kanban_leads" USING btree ("contact_id");--> statement-breakpoint
CREATE INDEX "lead_diagnostics_company_id_idx" ON "lead_diagnostics" USING btree ("company_id");--> statement-breakpoint
CREATE INDEX "marketing_ads_company_id_idx" ON "marketing_ads" USING btree ("company_id");--> statement-breakpoint
CREATE INDEX "marketing_adsets_company_id_idx" ON "marketing_adsets" USING btree ("company_id");--> statement-breakpoint
CREATE INDEX "marketing_campaigns_company_id_idx" ON "marketing_campaigns" USING btree ("company_id");--> statement-breakpoint
CREATE INDEX "marketing_credentials_company_id_idx" ON "marketing_credentials" USING btree ("company_id");--> statement-breakpoint
CREATE INDEX "marketing_social_profiles_company_id_idx" ON "marketing_social_profiles" USING btree ("company_id");--> statement-breakpoint
CREATE INDEX "media_assets_company_id_idx" ON "media_assets" USING btree ("company_id");--> statement-breakpoint
CREATE INDEX "message_reactions_company_id_idx" ON "message_reactions" USING btree ("company_id");--> statement-breakpoint
CREATE INDEX "message_templates_company_id_idx" ON "message_templates" USING btree ("company_id");--> statement-breakpoint
CREATE INDEX "message_templates_connection_id_idx" ON "message_templates" USING btree ("connection_id");--> statement-breakpoint
CREATE INDEX "messages_company_id_idx" ON "messages" USING btree ("company_id");--> statement-breakpoint
CREATE INDEX "messages_connection_id_idx" ON "messages" USING btree ("connection_id");--> statement-breakpoint
CREATE INDEX "notification_agents_company_id_idx" ON "notification_agents" USING btree ("company_id");--> statement-breakpoint
CREATE INDEX "notification_agents_connection_id_idx" ON "notification_agents" USING btree ("connection_id");--> statement-breakpoint
CREATE INDEX "persona_external_sources_company_id_idx" ON "persona_external_sources" USING btree ("company_id");--> statement-breakpoint
CREATE INDEX "system_errors_company_id_idx" ON "system_errors" USING btree ("company_id");--> statement-breakpoint
CREATE INDEX "tags_company_id_idx" ON "tags" USING btree ("company_id");--> statement-breakpoint
CREATE INDEX "templates_company_id_idx" ON "templates" USING btree ("company_id");--> statement-breakpoint
CREATE INDEX "user_notifications_company_id_idx" ON "user_notifications" USING btree ("company_id");--> statement-breakpoint
CREATE INDEX "users_to_teams_company_id_idx" ON "users_to_teams" USING btree ("company_id");--> statement-breakpoint
CREATE INDEX "voice_retry_queue_company_id_idx" ON "voice_retry_queue" USING btree ("company_id");--> statement-breakpoint
CREATE INDEX "voice_retry_queue_contact_id_idx" ON "voice_retry_queue" USING btree ("contact_id");